swagger: '2.0'

info:

  description:  This is the "zero gravity" API interface
  version: 1.0.0
  title: ZeroGravity 用户接口
  
host: localhost
basePath: /api/v1
tags: 
  - name: user
    description: 用户
  
  - name: idea
    description: 想法
  
  - name: searcher
    description: 查找
  
  - name: comment
    description: 评论
  
  - name: like
    description: 点赞
schemes: 
  - http
  - https
  
/register:
    post:
      tags:
        - user
      summary: 注册用户
      description: 直接输入账号和密码注册
      parameters:
        - name: data
          in: body
          description: post data
          schema:
            required:
              - account
              - password
            properties:
              name:
                type: string
                description: 用户昵称
              password:
                type: string
                description: 密码
      responses: 
        200:
          description: 注册成功,留住用户id
          schema:
            properties:
              account: 
                type: string
        400:
          description: 参数不全,客户端语法有问题
        401:
          description: 用户名或密码错误
          
/login: 
    post:
      tags: 
        - user
      summary: 登录
      description: 账号密码登录
      parameters:
        - name: data
          in: body
          description: post data
          schema:
            required:  
              - account: 
              - password:
            properties:
              account:
                type: string
                description: 用户账号
              password:
                type: string
                description: 用户密码
      responses:
        200:
          description: 登录成功
          schema:
            properties:
              token:
                type: string
                description: 传一个token保留,token就是account
        400:
          description: 参数不全
        401:
          description: 用户名或密码错误
          
          
/idea:
    post: 
      tags: 
        - idea
      summary: 新增想法
      parameters:
        - $ref: "#/parameters/token"
        - name: data
          in: body
          schema:
            properties:
              title: 
                type: string
              content:
                type: string
              picture:
                type: string
              user_id: 
                type: string
              publisher_time:
                type: string
                description: 新增想法内容
      responses:
        200:
          description: 发布成功
          schema:
            properties:
              user_id:
                type: string
              time:
                type: string
        400:
          description: 参数不全
        401:
          description: token错了, 权限不够
   
/like:
    post:
      tag:
        -like
      summary: 新增想法点赞记录
      parameters:
        - $ref: "#/parameters/token"
        - name: data
          in: body
           schema:
            properties:
              id:
                type: number
              idea_id:
                type: number
              beliked_id:
                type: string
              likers_id:
                type: string
                description: 想法点赞记录
      responses:
        200:
          description: 点赞成功
        404:
          description: 点赞失败
        401:
          description: 请先登陆
        
    post:
      tag:
        -like
      summary: 新增评论点赞记录
      parameters:
        - $ref: "#/parameters/token"
        - name: data
          in: body
           schema:
            properties:
              id:
                type: number
              comment_id:
                type: number
              beliked_id:
                type: string
              likers_id:
                type: string
                description: 想法点赞记录
      responses:
        200:
          description: 点赞成功
        404:
          description: 点赞失败
        401:
          description: 请先登陆
        
        
        
        
    put: 
      tags: 
        - like
      summary: 删除想法点赞记录
      parameters: 
        - $ref: "#/parameters/token"
        - name: user_id
          in: path
          required: true
          type: string
        - name: like_id
          in: body
          schema:
            type: array
            items:
              properties:
                user_id:
                  type: string
      responses:
        200:
          description: 删除成功
        404:
          description: 删除失败
        401:
          description: 请先登录
          
                        
    put: 
      tags: 
        - like
      summary: 删除评论点赞记录
      parameters: 
        - $ref: "#/parameters/token"
        - name: user_id
          in: path
          required: true
          type: string
        - name: like_id
          in: body
          schema:
            type: array
            items:
              properties:
                user_id:
                  type: string
      responses:
        200:
          description: 删除成功
        404:
          description: 删除失败
        401:
          description: 请先登录
          
                            
    
          
          
    
/comment:        
    post:
      tags:
        - comment
      summary: 新增评论记录
      parameters: 
        - $ref: "#/parameters/token"
        - name: content
          in: body
          required: true
        - name: release_date
          in: body
          required: true
          schema:
            properties: 
              
      responses:
        200:
          description: 评论发布成功
        404:
          description: 评论发布失败
        401:
          description: 请先登录
          
          
    put: 
      tags: 
        - comment
      summary: 删除评论记录
      parameters: 
        - $ref: "#/parameters/token"
        - name: user_id
          in: path
          required: true
          type: string
        - name: comment_id
          in: body
          schema:
            type: array
            items:
              properties:
                album_id:
                  type: integer
      responses:
        200:
          description: 删除成功
        404:
          description: 删除失败
        401:
          description: 请先登录
/user:
    get:
      tags: 
        - user
      summary: 用户收藏
      parameters: 
        - $ref: "#/parameters/token"
        - name: user_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: 收藏成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/user_collection"
        404:
          description: 没有该资源
        401:
          description: 请先登陆
    
    get:
      tags: 
        - user
      summary: 用户主页-我的想法
      parameters: 
        - name: user_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/user_idea"
        404:
          description: 没有该资源        
    
    get:
      tags:
        - user
      summary: 用户主页-我的账号，我的昵称，我的头像，我的能量值，
      parameters:
        - $ref: "#/parameters/token"
        - name: user_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: 获取成功
          schema:
            properties:
              user_id:
                type: string
              nickname: 
                type: string
              avater:
                type: string
              energy:
                type: number
        404:
          description: 没有该资源
        401:
          description: token错误，没有权限
    
    get:
      tags:
        - user
      summary: 用户主页-我的评论
      parameters: 
        - name: user_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/user_review"
        404:
          description: 没有该资源    
    
    put:
      tags:
        - user
      summary: 修改用户信息
      parameters:
        - $ref: "#/parameters/token"
        - name: user_id
          in: path
          required: true
          type: string
        - name: data
          in: body
          schema:
            properties:
              user_id:
                type: string
              avater:
                type: string
                description: 头像图片的url
              nickname:
                type: string 
      responses:
        200:
          description: OK
        401:
          description: token错了,权限不够
    
    put: 
      tags: 
        - user
      summary: 删除想法
      parameters: 
        - $ref: "#/parameters/token"
        - name: user_id
          in: path
          required: true
          type: string
        - name: idea_id
          in: body
          schema:
            type: array
            items:
              properties:
           
      responses:
        200:
          description: 删除成功
        401:
          description: token错误，没有权限 
          
    put: 
      tags: 
        - user
      summary: 删除评论
      parameters: 
        - $ref: "#/parameters/token"
        - name: user_id
          in: path
          required: true
          type: string
        - name: comment_id
          in: body
          schema:
            type: array
            items:
              properties:
           
      responses:
        200:
          description: 删除成功
        401:
          description: token错误，没有权限  
    
    
          
          
      
      
/searcher:
    get:
      tags: 
        - searcher
      summary: 想法查询
      parameters: 
        - $ref: "#/parameters/token"
        - name: idea_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: 查询成功
          schema:
            properties:
              comments:
                type: array
                items:
                  $ref: "#/definitions/user_idea"
        401:
        description: 请先登录
        404:
        description: 您所查找资源不存在


          
                    

definitions:
        
  user_idea:
      description: 一个信息块，同时显示想法和用户信息
    required:
      - idea_id
      - user_id
    properties:
      user_id:    #　这是路径里面user_id
        type: string
      nickname:
        type: string
      avater:
        type: string
      idea_id:
        type: integer
      title: 
        type: string
      content:
        type: string
      publiser_time: 
        type: string
      picture:
        type: string
        description: 传照片的url
      comment_sum:
        type: integer
      like_sum:
        type: integer
        description: 点赞数    
  
  idea:
    description: 想法信息
    
    properties:
      idea_id:
        type: integer
      content:
        type: string
      piblisher_time:
        type: data
      publisher_id:
        type: interger
      likes_sum:
        type: interger
      comments_sum:
        type: interger
      collection_sum:
        type: interger
        
  comment:
     description: 评论信息
    
    properties:
      comment_id:
        type: integer
      content:
        type: string
      piblisher_time:
        type: data
      publisher_id:
        type: interger
      likes_sum:
        type: interger
    

  user_comment:
      description: 用户信息和评论的表
      required:
        - comment_id
        - user_id
      properties:
        user_id:
          type: string
        nickname:
          type: string
        avater:
          type: string
        Comment_id:
          type: integer
        Content:
          type: string
        Time:
          type: string
        like_sum:
          type: integer
        Comment_like:
          description: 本用户是否点赞
          type: boolean
          
  user_idea:
      description: 用户信息和想法的表
      required:
        - idea_id
        - user_id
      properties:
        user_id:
          type: string
        nickname:
          type: string
        avater:
          type: string
        idea_id:
          type: integer
        content:
          type: string
        publisher_time:
          type: string
        like_sum:
          type: integer
        idea_like:
          description: 本用户是否点赞
          type: boolean
          
  user_like:
      description: 用户信息和点赞的表
      required:
        - like_id
        - user_id
        properties:
        user_id:
          type: string
        nickname:
          type: string
        avater:
          type: string
        idea_id:
          type: integer
        comment_id:
          type: integer
        
          
parameters:
  token:
      name: token
      in: header
      required: true
      type: string  
