// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terrms",
        "contact": {
            "name": "gongna",
            "email": "2036479155@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/api/v1/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "输入账号和密码登录",
                "parameters": [
                    {
                        "description": " Account 账户   AccountPassword 密码   ",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/api/v1/register": {
            "post": {
                "description": "用户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户输入账号和密码注册",
                "parameters": [
                    {
                        "description": "Account--账户 AccountPassword--账户密码\tNickName--昵称\tAvatar--头像 ",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/collection": {
            "get": {
                "description": "查看用户的收藏列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "summary": "查询用户的收藏列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userid用户ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit--偏移量指定开始返回记录之前要跳过的记录数 ",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page--限制指定要检索的记录数 ",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/collection.IdeaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            },
            "post": {
                "description": "新增收藏记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "summary": "添加收藏记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userid--用户的ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "IdeaId用户收藏的想法ID",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/collection.CreateCollectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除收藏记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "summary": "用户删除收藏记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userid--用户的ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "IdeaId用户收藏的想法ID",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/collection.DeleteCollectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/idea": {
            "post": {
                "description": "新增想法",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idea"
                ],
                "summary": "发布想法",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userid--用户ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Content 想法内容 || Space  1-\u003e情绪 2-\u003e脑洞 3-\u003e沉思 4-\u003e探梦 || Privacy  0-\u003e公开 1-\u003e隐私",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/idea.CreateIdeaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/idea/comment/:id/like": {
            "put": {
                "description": "新增评论点赞",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idea"
                ],
                "summary": "上传对用户发布的评论的点赞",
                "parameters": [
                    {
                        "type": "string",
                        "description": "LikersId点赞者的ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "CommentId 评论的ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/idea/detail/:id": {
            "get": {
                "description": "根据用户ID获取这个ID下发布的想法",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idea"
                ],
                "summary": "获取想法",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id--根据这个id判断发布的想法是否为私密，id为1是显示想法为私密发布，你无权查看",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "uid--用户ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/model.IdeaListItem"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除想法",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idea"
                ],
                "summary": "删除想法",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userid--用户ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/idea/detail/:id/comment": {
            "get": {
                "description": "想法的评论列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idea"
                ],
                "summary": "发布的想法下对应的评论",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uid--用户ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id--被评论的想法ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit--偏移量指定开始返回记录之前要跳过的记录数",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page--限制指定要检索的记录数 ",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/idea.CommentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            },
            "post": {
                "description": "Add comment records to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idea"
                ],
                "summary": "Add comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userid--用户的ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "CommentedId 被评论者的ID || Content 评论内容",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/idea.CreateCommentRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "IdeaId--想法ID",
                        "name": "idea_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/idea/detail/:id/comment/:comment_id": {
            "delete": {
                "description": "删除评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idea"
                ],
                "summary": "删除用户自己的评论",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id--评论的ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "uid --用户的ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/idea/detail/:id/like": {
            "put": {
                "description": "新增对想法的点赞",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idea"
                ],
                "summary": "上传想法点赞信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "LikersId点赞者的ID ",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/idea/liked": {
            "get": {
                "description": "获取想法被点赞的信息表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idea"
                ],
                "summary": "获取用户个人发布的想法被点赞的情况",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UserId--用户ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit--偏移量指定开始返回记录之前要跳过的记录数",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page--限制指定要检索的记录数 ",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/idea.IdeaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/idea/list": {
            "get": {
                "description": "显示用户发布的想法",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idea"
                ],
                "summary": "进入空间后看到的想法",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uid--用户ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit--偏移量指定开始返回记录之前要跳过的记录数",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page--限制指定要检索的记录数 ",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "userId--用户ID",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "privicy 获取想法的私有策略 0-\u003e不获取私有 1-\u003e获取私有 默认不获取 || 若获取则默认为获取自己的想法，需要服务判断 uid",
                        "name": "privicy",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "index--获取排序规则 0-\u003e默认时间排序 1-\u003e热度排序",
                        "name": "index",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/idea.IdeaResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/message/comment": {
            "get": {
                "description": "拉取评论我的消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "拉取评论我的消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "后端给前端的Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit--偏移量指定开始返回记录之前要跳过的记录数",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page--限制指定要检索的记录数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/message.GetMessageForCommentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/message/like": {
            "get": {
                "description": "获取点赞我的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "获取点赞我的信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Like information returned to front-end users",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit--偏移量指定开始返回记录之前要跳过的记录数",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page--限制指定要检索的记录数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/message.GetMessageForLikeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/message/readall": {
            "put": {
                "description": "修改信息为已读",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "修改信息为已读",
                "parameters": [
                    {
                        "type": "string",
                        "description": "后端给前端的token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/message/tip": {
            "get": {
                "description": "获取消息提示",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "获取消息提示",
                "parameters": [
                    {
                        "type": "string",
                        "description": "后端给前端的Token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/message.GetMessageTipResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/report": {
            "post": {
                "description": "举报用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "举报用户",
                "parameters": [
                    {
                        "description": "UserID--被举报的用户ID || Kind-- ||   Reason--原因   || CommentId --评论的ID|| ideaId--想法的ID",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/report.CreateReportRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "userId--用户ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/search": {
            "get": {
                "description": "获取搜索结果，结果为用户列表或想法列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "获取搜索结果",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page--限制指定要检索的记录数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit--偏移量指定开始返回记录之前要跳过的记录数",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "target为0模糊搜索想法  target为1模糊搜索用户 若想模糊查找用户请给target赋值为1传给服务器",
                        "name": "target",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "关键字",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "后端给前端的token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/search.UserListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除查询历史",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "删除查询历史",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId--用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "delete history删除历史记录",
                        "name": "h",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.History"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/search/histories": {
            "get": {
                "description": "获取历史记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "获取历史记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId--用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.History"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errno.Errno"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "put": {
                "description": "更改用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "更改用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UserId--用户ID",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Avatar头像|| NickName昵称",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateUserInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/api/v1/user/detail/:id": {
            "get": {
                "description": "得到用户所有的个人信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "得到用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId--用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/user.GetUserInfoResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.CreateUserRequest": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "account_password": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "account_password": {
                    "type": "string"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "collection.CreateCollectionRequest": {
            "type": "object",
            "properties": {
                "idea_id": {
                    "type": "integer"
                }
            }
        },
        "collection.DeleteCollectionRequest": {
            "type": "object",
            "properties": {
                "idea_id": {
                    "type": "integer"
                }
            }
        },
        "collection.IdeaResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.IdeaListItem"
                    }
                }
            }
        },
        "errno.Errno": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "idea.CommentResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CommentListItem"
                    }
                }
            }
        },
        "idea.CreateCommentRequest": {
            "type": "object",
            "properties": {
                "commented_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                }
            }
        },
        "idea.CreateIdeaRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "privacy": {
                    "description": "0-\u003e公开 1-\u003e隐私",
                    "type": "integer"
                },
                "space": {
                    "description": "1-\u003e情绪 2-\u003e脑洞 3-\u003e沉思 4-\u003e探梦",
                    "type": "integer"
                }
            }
        },
        "idea.IdeaResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.IdeaListItem"
                    }
                }
            }
        },
        "message.GetMessageForCommentResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MessageForCommentItem"
                    }
                }
            }
        },
        "message.GetMessageForLikeResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MessageForLikeItem"
                    }
                }
            }
        },
        "message.GetMessageTipResponse": {
            "type": "object",
            "properties": {
                "is_message": {
                    "type": "boolean"
                }
            }
        },
        "model.CommentListItem": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "commenter_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "idea_id": {
                    "type": "integer"
                },
                "liked": {
                    "description": "是否点赞",
                    "type": "boolean"
                },
                "likes_sum": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "release_date": {
                    "type": "string"
                }
            }
        },
        "model.History": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.IdeaListItem": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "comment_sum": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "idea_id": {
                    "type": "integer"
                },
                "liked": {
                    "description": "是否点赞",
                    "type": "boolean"
                },
                "likes_sum": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "publisher_id": {
                    "type": "integer"
                },
                "release_date": {
                    "type": "string"
                }
            }
        },
        "model.MessageForCommentItem": {
            "type": "object",
            "required": [
                "avatar",
                "content",
                "idea_id",
                "nickname",
                "reply",
                "user_id"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "idea_id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "reply": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.MessageForLikeItem": {
            "type": "object",
            "required": [
                "avatar",
                "comment_id",
                "content",
                "idea_id",
                "nickname",
                "user_id"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "comment_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "idea_id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "report.CreateReportRequest": {
            "type": "object",
            "properties": {
                "comment_id": {
                    "type": "integer"
                },
                "idea_id": {
                    "type": "integer"
                },
                "json": {
                    "type": "string"
                },
                "kind": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "search.IdeaResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.IdeaListItem"
                    }
                }
            }
        },
        "search.UserInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "energy": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "search.UserListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/search.UserInfo"
                    }
                }
            }
        },
        "user.GetUserInfoResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "energy": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "user.UpdateUserInfoRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "124.71.184.107",
	BasePath:    "",
	Schemes:     []string{"http"},
	Title:       "ZeroGravity",
	Description: "零重力APP",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
