// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terrms",
        "contact": {
            "name": "gongna",
            "email": "2036479155@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/collection": {
            "get": {
                "description": "Get a user's favorite record table and return it to the front end",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "summary": "Get a user's favorite record table",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/collection.IdeaResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new favorite record to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "summary": "Add favorite record",
                "parameters": [
                    {
                        "description": "Add a new favorite record to the database ",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/collection.CreateCollectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            },
            "delete": {
                "description": "Delete favorite records from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "summary": "Delete favorites",
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/api/v1/idea": {
            "post": {
                "description": "Add a thought record to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idea"
                ],
                "summary": "Add ideas",
                "parameters": [
                    {
                        "description": "Add a thought record to the database",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/idea.CreateIdeaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/api/v1/idea/detail/:id": {
            "delete": {
                "description": "Add a thought record to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idea"
                ],
                "summary": "Add ideas",
                "parameters": [
                    {
                        "description": "Add a thought record to the database",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/idea.CreateIdeaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "User login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "The user enters the account and password and then logs in",
                "parameters": [
                    {
                        "description": "The user enters the account and password and then logs in ",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/register": {
            "post": {
                "description": "User register",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User enters account and password to register",
                "parameters": [
                    {
                        "description": "The user enters the account and password and then register in ",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/api/v1/search": {
            "get": {
                "description": "Get search results, the result is a list of users or a list of ideas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Get search results",
                "parameters": [
                    {
                        "type": "integer",
                        "description": " search by page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": " search by limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": " search by target",
                        "name": "target",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "idea key word",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Get token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "$ref": "#/definitions/search.UserListResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete the history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Delete History",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": " delete history",
                        "name": "h",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.History"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/api/v1/search/histories": {
            "get": {
                "description": "Delete the history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Get Histories",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"username\":\"kong\"}}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.History"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.CreateUserRequest": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "account_password": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "account_password": {
                    "type": "string"
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "collection.CreateCollectionRequest": {
            "type": "object",
            "properties": {
                "collector_id": {
                    "type": "integer"
                },
                "idea_id": {
                    "type": "integer"
                }
            }
        },
        "collection.IdeaResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.IdeaListItem"
                    }
                }
            }
        },
        "idea.CommentResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CommentListItem"
                    }
                }
            }
        },
        "idea.CreateCommentRequest": {
            "type": "object",
            "properties": {
                "commented_id": {
                    "type": "integer"
                },
                "commenter_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                }
            }
        },
        "idea.CreateIdeaRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "publisher_id": {
                    "type": "integer"
                },
                "releaseDate": {
                    "type": "string"
                }
            }
        },
        "idea.IdeaResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.IdeaListItem"
                    }
                }
            }
        },
        "message.GetMessageForCommentResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MessageForCommentItem"
                    }
                }
            }
        },
        "message.GetMessageForLikeResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MessageForLikeItem"
                    }
                }
            }
        },
        "message.GetMessageTipResponse": {
            "type": "object",
            "properties": {
                "is_message": {
                    "type": "boolean"
                }
            }
        },
        "model.CommentListItem": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "commented_id": {
                    "type": "integer"
                },
                "commenter_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "liked": {
                    "description": "是否点赞",
                    "type": "boolean"
                },
                "likes_sum": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "release_date": {
                    "type": "string"
                }
            }
        },
        "model.History": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.IdeaListItem": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "comment_sum": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "idea_id": {
                    "type": "integer"
                },
                "liked": {
                    "description": "是否点赞",
                    "type": "boolean"
                },
                "likes_sum": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "publisher_id": {
                    "type": "integer"
                },
                "release_date": {
                    "type": "string"
                }
            }
        },
        "model.MessageForCommentItem": {
            "type": "object",
            "required": [
                "avatar",
                "content",
                "idea_id",
                "nickname",
                "reply",
                "user_id"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "idea_id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "reply": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.MessageForLikeItem": {
            "type": "object",
            "required": [
                "avatar",
                "comment_id",
                "content",
                "idea_id",
                "nickname",
                "user_id"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "comment_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "idea_id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "report.CreateReportRequest": {
            "type": "object",
            "properties": {
                "comment_id": {
                    "type": "integer"
                },
                "idea_id": {
                    "type": "integer"
                },
                "json": {
                    "type": "string"
                },
                "kind": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "search.IdeaResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.IdeaListItem"
                    }
                }
            }
        },
        "search.UserInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "energy": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "search.UserListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/search.UserInfo"
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "124.71.184.107",
	BasePath:    "",
	Schemes:     []string{"http"},
	Title:       "ZeroGravity",
	Description: "零重力APP",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
